
---
- name: Install build-packages
  hosts: build
  become: yes

  tasks:
  - name: Install open-jdk package
    apt:
      name: openjdk-8-jdk
      state: present



  - name: Install git
    apt:
      name: git
      state: present


  - name: Install maven
    apt:
      name: maven
      state: present

  - name: Git clone boxfuse
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /home/mikhail/boxfuse/
      clone: yes
      update: yes
  - name: Maven build app
    command: mvn package
    args:
      chdir: /home/mikhail/boxfuse/
  - name: Copy artefact to master node
    copy:
      src: /home/mikhail/boxfuse/target/hello-1.0.war
      dest: /home/mikhail/hello-1.0.war
      remote_src: yes

- name: Install prod-packages
  hosts: prod
  become: yes

  tasks:
    - name: Install tomcat9 package
      apt:
        name: tomcat9
        state: present

    - name: Copy arteafct to prod
      copy:
        src: /home/mikhail/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/
        remote_src: no
