---
version: '3'
services:
  maven:
    build: maven
    volumes:
      - dataapp:/boxfuse-sample-java-war-hello/target



  tomcat:
    image: tomcat:8-jre8
    volumes:
      - dataapp:/usr/local/tomcat/webapps
    ports:
      - 8080:8080
    depends_on:
      - maven


volumes:
  dataapp: